### ISSUE TITLE
Include apps from all workspaces

### ISSUE THREAD

**Issue by aral** [small-tech/catts#3]
You should be able to switch to apps in any workspace.

Currently, only apps in the current workspace are supported.

**Comment by janxkoci** [comment]
This should be optional, otherwise you ruin `Alt+Tab` for a lot of people. For instance, I use workspaces preciselly to have less programs in my alt+tab list. If you suddenly include all windows from all workspaces, the switcher becomes crowded and hence useless to me.

This is because alt-tabbing between more than 3 windows becomes pain very quickly (even 3 windows are pushing it, leading to occasional mistakes in selecting the right window).

**Comment by aral** [comment]
Hello again, that notice, once again (I know you’re on multiple issues, @janxkoci, apologies for the redundancy):

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

If this is still a problem for you, you can reach their issue tracker at https://github.com/elementary/gala/issues
