### ISSUE TITLE
Exit selected app in switcher using Ctrl + Q

### ISSUE THREAD

**Issue by aral** [small-tech/catts#5]
It is a productivity boost to be able to use the task switcher to close and app by quickly selecting its icon and, while continuing to hold down <kbd>Alt</kbd>, pressing <kbd>Ctrl</kbd> + <kbd>Q</kbd> to quit the selected app (especially when you want to quit several apps together). This is currently not supported by Catts.

The workaround is to switch to the app first and then press <kbd>Ctrl</kbd> + <kbd>Q</kbd>.

**Comment by tobehn** [comment]
Firs of, thank you for sticking hard to this topic and your efforts porting the Switcher to Odin - I am already using it.

Wouldn't it be even smoother just pressing `Q` while being in `alt` + `tab` and keep holding `alt`. By that the currently chosen app would be closed.
I think that's the default behavior on macOS. At least I am very used to that kind of clothing a couple of apps in one go.

**Comment by janxkoci** [comment]
My 2 cents:

- How do you hold `Alt` and press `Ctrl+Q` at the same time? I do both with left hand and the fingers just don't bend like that :thinking: 
- This action can be done easily with the multitasking view. It provides both a switcher and an ability to close apps too.
  - Since macOS doesn't have this feature, some of its users tend to suggest rather cryptic workarounds, such as the unintuitive shortcut above :wink:

**Comment by aral** [comment]
Hey folks, a quick update:

I’m about to archive Catts as it has now been included as part of elementary OS in Gala. Further development work will be ongoing there.

If this is still a problem for you, you can reach their issue tracker at https://github.com/elementary/gala/issues
